import "../globals.css";
import { Inter } from "next/font/google";



const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default async function SignIn_Layout({ children }) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="register">
          <div className="register-col-1">{children}</div>
          <div className="register-col-2"></div>
        </main>
      </body>
    </html>
  );
}
