import { Inter } from "next/font/google";
import "../globals.css";
import Header from "../components/header/header";
import MainBody from "../components/main-layout/mainBody";

import { auth } from "@/auth";
import { redirect } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function Layout({ children }) {
  const session = await auth();
  console.log(session);
  if (!session?.user) {
    redirect("/login");
  }
  return (
    <html lang="en">
      <body className={inter.className}>
        <main>
          <Header user={session.user.name} />
          <MainBody children={children} />
        </main>
      </body>
    </html>
  );
}
