import { Inter } from "next/font/google";
import "../globals.css";
import Header from "../components/header/header";
import MainBody from "../components/main-layout/mainBody";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main>
          <Header />
          <MainBody children={children} />
          {/* <div className="col-2">{children}</div> */}
        </main>
      </body>
    </html>
  );
}
